const stories = [
  {
    id: 1,
    desktop: "/stories/desktop/mountains.jpg",
    tablet: "/stories/desktop/mountains.jpg",
    mobile: "/stories/mobile/mountains.jpg",
    date: "April 16th 2020",
    name: "Mountains",
    author: "John Appleseed",
    alt: "Mountains image",
  },
  {
    id: 2,
    desktop: "/stories/desktop/cityscapes.jpg",
    tablet: "/stories/desktop/cityscapes.jpg",
    mobile: "/stories/mobile/cityscapes.jpg",
    date: "April 14th 2020",
    name: "Sunset Cityscapes",
    author: "Benjamin Cruz",
    alt: "Sunset Cityscapes image",
  },
  {
    id: 3,
    desktop: "/stories/desktop/18-days-voyage.jpg",
    tablet: "/stories/desktop/18-days-voyage.jpg",
    mobile: "/stories/mobile/18-days-voyage.jpg",
    date: "April 11th 2020",
    name: "18 Days Voyage",
    author: "Alexei Borodin",
    alt: "Voyage image",
  },
  {
    id: 4,
    desktop: "/stories/desktop/architecturals.jpg",
    tablet: "/stories/desktop/architecturals.jpg",
    mobile: "/stories/mobile/architecturals.jpg",
    date: "April 19th 2020",
    name: "Architecturals",
    author: "Samantha Broke",
    alt: "Architecturals image",
  },
  {
    id: 5,
    desktop: "/stories/desktop/world-tour.jpg",
    tablet: "/stories/desktop/world-tour.jpg",
    mobile: "/stories/mobile/world-tour.jpg",
    date: "April 7th 2020",
    name: "World Tour 2019",
    author: "Timothy Wagner",
    alt: "Tour image",
  },
  {
    id: 6,
    desktop: "/stories/desktop/unforseen-corners.jpg",
    tablet: "/stories/desktop/unforseen-corners.jpg",
    mobile: "/stories/mobile/unforseen-corners.jpg",
    date: "April 3rd 2020",
    name: "Unforseen Corners",
    author: "William Malcolm",
    alt: "Unforseen Corners image",
  },
  {
    id: 7,
    desktop: "/stories/desktop/king-on-africa.jpg",
    tablet: "/stories/desktop/king-on-africa.jpg",
    mobile: "/stories/mobile/king-on-africa.jpg",
    date: "March 29th 2020",
    name: "King of Africa Part II",
    author: "Tim Hillenburg",
    alt: "Lion image",
  },
  {
    id: 8,
    desktop: "/stories/desktop/trip-to-nowhere.jpg",
    tablet: "/stories/desktop/trip-to-nowhere.jpg",
    mobile: "/stories/mobile/trip-to-nowhere.jpg",
    date: "March 21st 2020",
    name: "The Trip to Nowhere",
    author: "Felicia Rourke",
    alt: "Trip image",
  },
  {
    id: 9,
    desktop: "/stories/desktop/rage-of-the-sea.jpg",
    tablet: "/stories/desktop/rage-of-the-sea.jpg",
    mobile: "/stories/mobile/rage-of-the-sea.jpg",
    date: "March 19th 2020",
    name: "Rage of The sea",
    author: "Mohammed Abdul",
    alt: "Sea image",
  },
  {
    id: 10,
    desktop: "/stories/desktop/running-free.jpg",
    tablet: "/stories/desktop/running-free.jpg",
    mobile: "/stories/mobile/running-free.jpg",
    date: "March 16th 2020",
    name: "Running Free",
    author: "Michelle",
    alt: "Horses image",
  },
  {
    id: 11,
    desktop: "/stories/desktop/behind-the-waves.jpg",
    tablet: "/stories/desktop/behind-the-waves.jpg",
    mobile: "/stories/mobile/behind-the-waves.jpg",
    date: "March 11th 2020",
    name: "Behind the Waves",
    author: "Lamarr Wilson",
    alt: "Waves image",
  },
  {
    id: 12,
    desktop: "/stories/desktop/calm-waters.jpg",
    tablet: "/stories/desktop/calm-waters.jpg",
    mobile: "/stories/mobile/calm-waters.jpg",
    date: "March 9th 2020",
    name: "Calm Waters",
    author: "Samata Brooke",
    alt: "Waters image",
  },
  {
    id: 13,
    desktop: "/stories/desktop/milky-way",
    tablet: "/stories/desktop/milky-way",
    mobile: "/stories/mobile/milky-way",
    date: "March 5th 2020",
    name: "The Milky Way",
    author: "Benjamin Cruz",
    alt: "Milky Way image",
  },
  {
    id: 14,
    desktop: "/stories/desktop/dark-forest.jpg",
    tablet: "/stories/desktop/dark-forest.jpg",
    mobile: "/stories/mobile/dark-forest.jpg",
    date: "March 4th 2020",
    name: "Night at The Dark Forest",
    author: "Mohammed Abdul",
    alt: "Dark Forset image",
  },
  {
    id: 15,
    desktop: "/stories/desktop/somwarpet.jpg",
    tablet: "/stories/desktop/somwarpet.jpg",
    mobile: "/stories/mobile/somwarpet.jpg",
    date: "March 1st 2020",
    name: "Somwarpet's Beauty",
    author: "Michele",
    alt: "Somwarpet image",
  },
  {
    id: 16,
    desktop: "/stories/desktop/land-of-dreams.jpg",
    tablet: "/stories/desktop/land-of-dreams.jpg",
    mobile: "/stories/mobile/land-of-dreams.jpg",
    date: "Feburary 25th 2020",
    name: "Land of Dreams",
    author: "William Malcolm",
    alt: "Land image",
  },
]

export { stories }
